# Generated by Django 5.2.4 on 2025-07-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concentrations',
            fields=[
                ('idconcentrationdata', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'concentrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('idcountrydata', models.IntegerField(primary_key=True, serialize=False)),
                ('countrycode', models.CharField(blank=True, max_length=5, null=True)),
                ('continentcode', models.CharField(blank=True, max_length=5, null=True)),
                ('countryname', models.CharField(blank=True, max_length=100, null=True)),
                ('fullname', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataTables',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_tables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eda20222023',
            fields=[
                ('idregistrantdata', models.IntegerField(primary_key=True, serialize=False)),
                ('groupreg', models.CharField(blank=True, max_length=255, null=True)),
                ('asalsekolah', models.CharField(blank=True, max_length=255, null=True)),
                ('graduationyear', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('finalscore', models.FloatField(blank=True, null=True)),
                ('isenrolled', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Data Pendaftar 2022/2023',
                'verbose_name_plural': 'Data Pendaftar 2022/2023',
                'db_table': 'eda_2022_2023',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eda20232024',
            fields=[
                ('idregistrantdata', models.IntegerField(primary_key=True, serialize=False)),
                ('groupreg', models.CharField(blank=True, max_length=255, null=True)),
                ('asalsekolah', models.CharField(blank=True, max_length=255, null=True)),
                ('graduationyear', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('finalscore', models.FloatField(blank=True, null=True)),
                ('isenrolled', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Data Pendaftar 2023/2024',
                'verbose_name_plural': 'Data Pendaftar 2023/2024',
                'db_table': 'eda_2023_2024',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'genders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupRegistrasi',
            fields=[
                ('iddatagroupreg', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'group_registrasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JenisSekolah',
            fields=[
                ('idschooltypedata', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jenis_sekolah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JurusanSekolah',
            fields=[
                ('idschooljurusandata', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'jurusan_sekolah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('idmajordata', models.IntegerField(primary_key=True, serialize=False)),
                ('idfacultydata', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('displayname', models.CharField(blank=True, max_length=150, null=True)),
                ('majorcode', models.CharField(blank=True, max_length=10, null=True)),
                ('is_pagi', models.IntegerField(blank=True, null=True)),
                ('is_malam', models.IntegerField(blank=True, null=True)),
                ('iddataeducationlevel', models.IntegerField(blank=True, null=True)),
                ('idspecialtermsrankdata', models.IntegerField(blank=True, null=True)),
                ('linkvideo', models.TextField(blank=True, null=True)),
                ('akreditasi', models.CharField(blank=True, max_length=5, null=True)),
                ('is_displayreportrevenue', models.IntegerField(blank=True, null=True)),
                ('ipcreated', models.CharField(blank=True, max_length=50, null=True)),
                ('datecreated', models.CharField(blank=True, max_length=50, null=True)),
                ('idcreated', models.IntegerField(blank=True, null=True)),
                ('ipmodify', models.CharField(blank=True, max_length=50, null=True)),
                ('datemodify', models.CharField(blank=True, max_length=50, null=True)),
                ('idmodify', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'major',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Provinsi',
                'db_table': 'provinsi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Regencies',
                'db_table': 'regency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registrants',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.TextField(blank=True, null=True)),
                ('idnumber', models.TextField(blank=True, null=True)),
                ('school', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('regtype', models.TextField(blank=True, null=True)),
                ('regtime', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registrants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrasiKhusus',
            fields=[
                ('iddataregkhusustype', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'registrasi_khusus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipeKelas',
            fields=[
                ('iddataclasstype', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipe_kelas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipeRegistrasi',
            fields=[
                ('iddataregtype', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('displayname', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_displayname', models.CharField(blank=True, max_length=100, null=True)),
                ('groupreg_displayname', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tipe_registrasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
