# Generated by Django 5.2.4 on 2025-07-22 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eda20232024',
            fields=[
                ('idregistrantdata', models.IntegerField(primary_key=True, serialize=False)),
                ('groupreg', models.IntegerField(blank=True, null=True)),
                ('regtype', models.IntegerField(blank=True, null=True)),
                ('asalsekolah', models.TextField(blank=True, null=True)),
                ('graduationyear', models.IntegerField(blank=True, null=True)),
                ('nationality', models.IntegerField(blank=True, null=True)),
                ('iddataprovinces', models.IntegerField(blank=True, null=True)),
                ('iddataregencies', models.IntegerField(blank=True, null=True)),
                ('finalscore', models.FloatField(blank=True, null=True)),
                ('rank', models.TextField(blank=True, null=True)),
                ('iddatapassingstatus', models.IntegerField(blank=True, null=True)),
                ('ispaid', models.BooleanField(blank=True, null=True)),
                ('isenrolled', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Data Pendaftar 2023/2024',
                'verbose_name_plural': 'Data Pendaftar 2023/2024',
                'db_table': 'eda_2023_2024',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'provinsi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetUpload',
            fields=[
                ('id_data', models.AutoField(primary_key=True, serialize=False)),
                ('nama_data', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='datasets/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('tanggal_approve', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_files', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dataset_upload_history',
                'ordering': ['-tanggal_upload'],
            },
        ),
    ]
